DROP TABLE IF EXISTS `pessoa`;
CREATE TABLE `pessoa` (
  `id`   BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;
